DROP TABLE IF EXISTS dev.Diagram ;

-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE IF NOT EXISTS dev.Diagram (
  idDiagram SERIAL NOT NULL,
  idUml VARCHAR(45) NULL,
  name VARCHAR(45) NULL,
  type VARCHAR(45) NULL,
  umlId VARCHAR(45) NULL,
  PRIMARY KEY (idDiagram))
;