DROP TABLE IF EXISTS dev.Diagram ;

-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE IF NOT EXISTS dev.Diagram (
  id_diagram SERIAL NOT NULL,
  id_uml VARCHAR(45) NULL,
  name VARCHAR(45) NULL,
  type VARCHAR(45) NULL,
  PRIMARY KEY (id_diagram))
;