DROP TABLE IF EXISTS dev.Type ;

-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE IF NOT EXISTS dev.Type (
  id_type SERIAL NOT NULL,
  id_uml VARCHAR(45) NULL,
  name VARCHAR(45) NULL,
  PRIMARY KEY (id_type))
;
