DROP TABLE IF EXISTS dev.Type ;

-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE IF NOT EXISTS dev.Type (
  idType SERIAL NOT NULL,
  idUml VARCHAR(45) NULL,
  name VARCHAR(45) NULL,
  PRIMARY KEY (idType))
;
